### PR TITLE
Add auth parameter to CLI

### PR DESCRIPTION
**Pull request by sklise**
Hey!

Thanks so much for making this module!!! I added the ability to set an auth password and it worked for me, so here is a PR about it.

Added the `-a` flag for the CLI to set a password. It defaults to an empty string.

I'm not really sure how `Cake` works and after running it for whatever reason the javascript files are now coffeescript, so I added the coffee-script register line.

### CODE REVIEW

**Comment by jonesdhtx** [comment]
+1

**Comment by devoto13** [comment]
Great patch! Hope it'll be merged soon.

**Comment by tallesl** [comment]
:+1:

It's unusable for me without authentication.

**Comment by and-go** [comment]
+1...need the -a option...

Thisi is a great tool...

**Comment by fallanic** [comment]
would it be possible to merge that PR? this tool looks awesome but will be unusable for me too without authentication

**Comment by jeremyfa** [comment]
I can't merge this as is. It seems that multiples things have been changed. There should be no coffee file in the bin/ directory, which is only supposed to have generated javascript files. Maybe there was a problem when installing findit dependency. I will have to ensure the correct version of findit does get installed for the Cakefile, but I can definitly not merge this.
Please, create a new PR with only the changes related to auth param, and I will merge it (if it works of course ;) )

Thanks!

**Pull request closed without merging**
