### PR TITLE
Added support for selecting database

### PR DESCRIPTION
**Pull request by kosmikko**
Otherwise dump only works with database 0
http://redis.io/commands/select

### CODE REVIEW

**Comment by jeremyfa** [comment]
This feature totally makes sense, thanks. Just one thing:

```
params.database ?= null
```

Instead I would put the following, in order to be sure default will be zero, and not "null casted to zero":

```
params.database ?= 0
```

What do you think?

**Comment by kosmikko** [comment]
Yeah, good idea.

**Comment by nisaacson** [comment]
Any reason this cannot be merged?

**Comment by jeremyfa** [comment]
This should be fixed with https://github.com/jeremyfa/node-redis-dump/pull/4.

Tell me if there is still something missing.

**Pull request closed without merging**
